///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ranorexDesktopFramework
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ranorexDesktopFrameworkRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("38dfdf3b-adb0-4aab-8721-9ad46ff2975e")]
    public partial class ranorexDesktopFrameworkRepository : RepoGenBaseFolder
    {
        static ranorexDesktopFrameworkRepository instance = new ranorexDesktopFrameworkRepository();
        ranorexDesktopFrameworkRepositoryFolders.MyAssaysAppAppFolder _myassaysapp;

        /// <summary>
        /// Gets the singleton class instance representing the ranorexDesktopFrameworkRepository element repository.
        /// </summary>
        [RepositoryFolder("38dfdf3b-adb0-4aab-8721-9ad46ff2975e")]
        public static ranorexDesktopFrameworkRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ranorexDesktopFrameworkRepository() 
            : base("ranorexDesktopFrameworkRepository", "/", null, 0, false, "38dfdf3b-adb0-4aab-8721-9ad46ff2975e", ".\\RepositoryImages\\ranorexDesktopFrameworkRepository38dfdf3b.rximgres")
        {
            _myassaysapp = new ranorexDesktopFrameworkRepositoryFolders.MyAssaysAppAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("38dfdf3b-adb0-4aab-8721-9ad46ff2975e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MyAssaysApp folder.
        /// </summary>
        [RepositoryFolder("fd0dcffe-2fc0-4b5f-9493-455cf6f84f4b")]
        public virtual ranorexDesktopFrameworkRepositoryFolders.MyAssaysAppAppFolder MyAssaysApp
        {
            get { return _myassaysapp; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class ranorexDesktopFrameworkRepositoryFolders
    {
        /// <summary>
        /// The MyAssaysAppAppFolder folder.
        /// </summary>
        [RepositoryFolder("fd0dcffe-2fc0-4b5f-9493-455cf6f84f4b")]
        public partial class MyAssaysAppAppFolder : RepoGenBaseFolder
        {
            ranorexDesktopFrameworkRepositoryFolders.NewProtocolWizzardFolder _newprotocolwizzard;
            ranorexDesktopFrameworkRepositoryFolders.SampleTypesEditorFolder _sampletypeseditor;
            RepoItemInfo _protocolsbuttonInfo;
            RepoItemInfo _homenewbuttonInfo;

            /// <summary>
            /// Creates a new MyAssaysApp  folder.
            /// </summary>
            public MyAssaysAppAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyAssaysApp", "/form[@processname='MyAssays.Desktop.Explorer']", parentFolder, 30000, null, true, "fd0dcffe-2fc0-4b5f-9493-455cf6f84f4b", "")
            {
                _newprotocolwizzard = new ranorexDesktopFrameworkRepositoryFolders.NewProtocolWizzardFolder(this);
                _sampletypeseditor = new ranorexDesktopFrameworkRepositoryFolders.SampleTypesEditorFolder(this);
                _protocolsbuttonInfo = new RepoItemInfo(this, "ProtocolsButton", "container/?/?/?/?/?/tabpagelist[@automationid='TabControl']/tabpage[@index='2']/container[@automationid='PART_DockPanel']/text[@caption='Protocols']", 30000, null, "87ec1ae1-8e8d-4a47-8a63-49e624afea2d");
                _homenewbuttonInfo = new RepoItemInfo(this, "HomeNewButton", "container//list[@automationid='Ribbon']/list[1]/list[3]/element[@automationid='NewFileRibbonButton']/?/?/element[@automationid='InnerPath']", 30000, null, "6e881b55-86b2-4a62-b2d8-e13378e45ff9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fd0dcffe-2fc0-4b5f-9493-455cf6f84f4b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fd0dcffe-2fc0-4b5f-9493-455cf6f84f4b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProtocolsButton item.
            /// </summary>
            [RepositoryItem("87ec1ae1-8e8d-4a47-8a63-49e624afea2d")]
            public virtual Ranorex.Text ProtocolsButton
            {
                get
                {
                    return _protocolsbuttonInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ProtocolsButton item info.
            /// </summary>
            [RepositoryItemInfo("87ec1ae1-8e8d-4a47-8a63-49e624afea2d")]
            public virtual RepoItemInfo ProtocolsButtonInfo
            {
                get
                {
                    return _protocolsbuttonInfo;
                }
            }

            /// <summary>
            /// The HomeNewButton item.
            /// </summary>
            [RepositoryItem("6e881b55-86b2-4a62-b2d8-e13378e45ff9")]
            public virtual Ranorex.Unknown HomeNewButton
            {
                get
                {
                    return _homenewbuttonInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The HomeNewButton item info.
            /// </summary>
            [RepositoryItemInfo("6e881b55-86b2-4a62-b2d8-e13378e45ff9")]
            public virtual RepoItemInfo HomeNewButtonInfo
            {
                get
                {
                    return _homenewbuttonInfo;
                }
            }

            /// <summary>
            /// The NewProtocolWizzard folder.
            /// </summary>
            [RepositoryFolder("45075ce5-f647-445c-bd95-a9d7d66a9612")]
            public virtual ranorexDesktopFrameworkRepositoryFolders.NewProtocolWizzardFolder NewProtocolWizzard
            {
                get { return _newprotocolwizzard; }
            }

            /// <summary>
            /// The SampleTypesEditor folder.
            /// </summary>
            [RepositoryFolder("1069d048-efe7-44b8-80b3-e717887029cc")]
            public virtual ranorexDesktopFrameworkRepositoryFolders.SampleTypesEditorFolder SampleTypesEditor
            {
                get { return _sampletypeseditor; }
            }
        }

        /// <summary>
        /// The NewProtocolWizzardFolder folder.
        /// </summary>
        [RepositoryFolder("45075ce5-f647-445c-bd95-a9d7d66a9612")]
        public partial class NewProtocolWizzardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nextbuttonInfo;
            RepoItemInfo _iwillenterinmydataradioInfo;
            RepoItemInfo _managetypesbuttonInfo;
            RepoItemInfo _expectednewdefaulttypebynameInfo;
            RepoItemInfo _maximizewindowbuttonInfo;

            /// <summary>
            /// Creates a new NewProtocolWizzard  folder.
            /// </summary>
            public NewProtocolWizzardFolder(RepoGenBaseFolder parentFolder) :
                    base("NewProtocolWizzard", "?/?", parentFolder, 30000, null, false, "45075ce5-f647-445c-bd95-a9d7d66a9612", "")
            {
                _nextbuttonInfo = new RepoItemInfo(this, "NextButton", "container[1]/container/button[@text='Next']", 30000, null, "265082c5-2723-457a-a95e-bf8389514d05");
                _iwillenterinmydataradioInfo = new RepoItemInfo(this, "IwillEnterInMyDataRadio", "element/container/container/container[1]/radiobutton[@text~'^I\\ will\\ enter/paste\\ in\\ my\\ ']/element[@automationid='optionMark']", 30000, null, "b45a6f6e-84d2-40a1-a455-e6c760ba4299");
                _managetypesbuttonInfo = new RepoItemInfo(this, "ManageTypesButton", "element/container/container/container/container/button[@automationid='AdvancedViewButton']", 30000, null, "0d2ddaa8-e3e8-4530-9206-cae24bee0585");
                _expectednewdefaulttypebynameInfo = new RepoItemInfo(this, "ExpectedNewDefaultTypeByName", "element/container/container/container/?/?/list[@automationid='SampleTypesSimplifiedView']/container/?/container[2]/text[@caption='SampleType29']", 30000, null, "1f74c442-6894-4344-b703-f5f2cbfcc2e2");
                _maximizewindowbuttonInfo = new RepoItemInfo(this, "MaximizeWindowButton", "button[@automationid='Maximize']", 30000, null, "7e553be7-111c-4957-9067-c7ffbcd754d6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("45075ce5-f647-445c-bd95-a9d7d66a9612")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("45075ce5-f647-445c-bd95-a9d7d66a9612")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NextButton item.
            /// </summary>
            [RepositoryItem("265082c5-2723-457a-a95e-bf8389514d05")]
            public virtual Ranorex.Button NextButton
            {
                get
                {
                    return _nextbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NextButton item info.
            /// </summary>
            [RepositoryItemInfo("265082c5-2723-457a-a95e-bf8389514d05")]
            public virtual RepoItemInfo NextButtonInfo
            {
                get
                {
                    return _nextbuttonInfo;
                }
            }

            /// <summary>
            /// The IwillEnterInMyDataRadio item.
            /// </summary>
            [RepositoryItem("b45a6f6e-84d2-40a1-a455-e6c760ba4299")]
            public virtual Ranorex.Unknown IwillEnterInMyDataRadio
            {
                get
                {
                    return _iwillenterinmydataradioInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The IwillEnterInMyDataRadio item info.
            /// </summary>
            [RepositoryItemInfo("b45a6f6e-84d2-40a1-a455-e6c760ba4299")]
            public virtual RepoItemInfo IwillEnterInMyDataRadioInfo
            {
                get
                {
                    return _iwillenterinmydataradioInfo;
                }
            }

            /// <summary>
            /// The ManageTypesButton item.
            /// </summary>
            [RepositoryItem("0d2ddaa8-e3e8-4530-9206-cae24bee0585")]
            public virtual Ranorex.Button ManageTypesButton
            {
                get
                {
                    return _managetypesbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ManageTypesButton item info.
            /// </summary>
            [RepositoryItemInfo("0d2ddaa8-e3e8-4530-9206-cae24bee0585")]
            public virtual RepoItemInfo ManageTypesButtonInfo
            {
                get
                {
                    return _managetypesbuttonInfo;
                }
            }

            /// <summary>
            /// The ExpectedNewDefaultTypeByName item.
            /// </summary>
            [RepositoryItem("1f74c442-6894-4344-b703-f5f2cbfcc2e2")]
            public virtual Ranorex.Text ExpectedNewDefaultTypeByName
            {
                get
                {
                    return _expectednewdefaulttypebynameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ExpectedNewDefaultTypeByName item info.
            /// </summary>
            [RepositoryItemInfo("1f74c442-6894-4344-b703-f5f2cbfcc2e2")]
            public virtual RepoItemInfo ExpectedNewDefaultTypeByNameInfo
            {
                get
                {
                    return _expectednewdefaulttypebynameInfo;
                }
            }

            /// <summary>
            /// The MaximizeWindowButton item.
            /// </summary>
            [RepositoryItem("7e553be7-111c-4957-9067-c7ffbcd754d6")]
            public virtual Ranorex.Button MaximizeWindowButton
            {
                get
                {
                    return _maximizewindowbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MaximizeWindowButton item info.
            /// </summary>
            [RepositoryItemInfo("7e553be7-111c-4957-9067-c7ffbcd754d6")]
            public virtual RepoItemInfo MaximizeWindowButtonInfo
            {
                get
                {
                    return _maximizewindowbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The SampleTypesEditorFolder folder.
        /// </summary>
        [RepositoryFolder("1069d048-efe7-44b8-80b3-e717887029cc")]
        public partial class SampleTypesEditorFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addsampletypebuttonInfo;
            RepoItemInfo _sampletypeseditorokbuttonInfo;

            /// <summary>
            /// Creates a new SampleTypesEditor  folder.
            /// </summary>
            public SampleTypesEditorFolder(RepoGenBaseFolder parentFolder) :
                    base("SampleTypesEditor", "", parentFolder, 0, null, false, "1069d048-efe7-44b8-80b3-e717887029cc", "")
            {
                _addsampletypebuttonInfo = new RepoItemInfo(this, "AddSampleTypeButton", "container/?/?/button[@text='Add Sample Type']", 30000, null, "e009bb6a-f7ac-41bf-89a3-ed0bc967f514");
                _sampletypeseditorokbuttonInfo = new RepoItemInfo(this, "SampleTypesEditorOkButton", "container/?/?/button[@text='OK']", 30000, null, "e3bb66ba-5519-4dae-9d9c-e5978df56dce");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1069d048-efe7-44b8-80b3-e717887029cc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddSampleTypeButton item.
            /// </summary>
            [RepositoryItem("e009bb6a-f7ac-41bf-89a3-ed0bc967f514")]
            public virtual Ranorex.Button AddSampleTypeButton
            {
                get
                {
                    return _addsampletypebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddSampleTypeButton item info.
            /// </summary>
            [RepositoryItemInfo("e009bb6a-f7ac-41bf-89a3-ed0bc967f514")]
            public virtual RepoItemInfo AddSampleTypeButtonInfo
            {
                get
                {
                    return _addsampletypebuttonInfo;
                }
            }

            /// <summary>
            /// The SampleTypesEditorOkButton item.
            /// </summary>
            [RepositoryItem("e3bb66ba-5519-4dae-9d9c-e5978df56dce")]
            public virtual Ranorex.Button SampleTypesEditorOkButton
            {
                get
                {
                    return _sampletypeseditorokbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SampleTypesEditorOkButton item info.
            /// </summary>
            [RepositoryItemInfo("e3bb66ba-5519-4dae-9d9c-e5978df56dce")]
            public virtual RepoItemInfo SampleTypesEditorOkButtonInfo
            {
                get
                {
                    return _sampletypeseditorokbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}