///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ranorexDesktopFramework
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ranorexDesktopFrameworkRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("38dfdf3b-adb0-4aab-8721-9ad46ff2975e")]
    public partial class ranorexDesktopFrameworkRepository : RepoGenBaseFolder
    {
        static ranorexDesktopFrameworkRepository instance = new ranorexDesktopFrameworkRepository();

        /// <summary>
        /// Gets the singleton class instance representing the ranorexDesktopFrameworkRepository element repository.
        /// </summary>
        [RepositoryFolder("38dfdf3b-adb0-4aab-8721-9ad46ff2975e")]
        public static ranorexDesktopFrameworkRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ranorexDesktopFrameworkRepository() 
            : base("ranorexDesktopFrameworkRepository", "/", null, 0, false, "38dfdf3b-adb0-4aab-8721-9ad46ff2975e", ".\\RepositoryImages\\ranorexDesktopFrameworkRepository38dfdf3b.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("38dfdf3b-adb0-4aab-8721-9ad46ff2975e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class ranorexDesktopFrameworkRepositoryFolders
    {
    }
#pragma warning restore 0436
}